#!/bin/bash
# This will later get integrated into the extract-events main loop.

# Configuration
timesfile=times # pre-filtered joins/leaves/restarts
slotsec=3600 # 3600 seconds/hour, 86400 seconds/day

# Init
declare -A jointimes # holds the last time the player joined
declare -A slots # holds the time and names of players online at that timeframe

# Coloring
cr="\e[1;49;31m"
cg="\e[1;49;32m"
cy="\e[1;49;33m"
cb="\e[1;49;34m"
cn="\e[0;0;0m"

# Adds the player to all slots he was online at
leave() {
	jointime="${jointimes["$name"]}"
	if [ -z "$jointime" ]; then
		echo -e "${cr}ERROR${cn} \"$name\" left without joining. \"$line\""
	else
		diff="$(( $seconds - $jointime ))"
		for slot in `seq $(($jointime / $slotsec)) $(($seconds / $slotsec))`; do
			if [ -z "${slots["$slot"]}" ]; then
				slots["$slot"]="$(( $slot * $slotsec ))" # put the time in seconds at the beginning of the slot
			fi
			if `echo "${slots["$slot"]}" | grep -qv "$name"`; then
				slots["$slot"]="${slots["$slot"]} $name"
			fi
		done
	fi
	jointimes["$name"]=
	#jointimes["$name"]="$seconds" # TODO catch bugs by changing this line
}

# Go through all pre-filtered joins/leaves/restarts
while read line; do
	seconds="`echo $line | cut -b1-10`" # e.g. 1407874849
	action="`echo $line | cut -b12- | grep -o '^[^ ]*'`" # joined/left/restart
	name="`echo $line | cut -b12- | grep -v restart | grep -o '[^ ]*$'`" # player name w/o color escape codes
	#echo -en "${cy}DEBUG${cn} $line \t-- ${cb}before:${cn} ${cg}jointimes=${cn}'${!jointimes[@]}' '${jointimes[@]}'"
	#if [ -n "$name" ]; then echo -e " ${cg}join[$name]=${cn}'${jointimes["$name"]}'"; else echo; fi
	case $action in
		joined)
			jointimes["$name"]="$seconds"
			;;
		left) leave
			;;
		restart)
			for name in "${!jointimes[@]}"; do # overwrite the empty name field
				if [ -n "${jointimes["$name"]}" ]; then # only leave if online
					leave
				fi
			done
			;;
		*) echo -e "${cr}ERROR${cn} Invalid action \"$action\". \"$line\""
			;;
	esac
	#echo -en "${cy}DEBUG${cn} $line \t-- ${cb}after:${cn}  ${cg}jointimes=${cn}'${!jointimes[@]}' '${jointimes[@]}'"
	#if [ -n "$name" ]; then echo -e " ${cg}join[$name]=${cn}'${jointimes["$name"]}'"; else echo; fi
done < $timesfile

# format the slot contents: 1407874849 Sun 12.03.2014 12:34 gjum notch
outarr= # stores all formatted filled slots, separated by newlines
for slot in "${slots[@]}"; do
	seconds="`echo $slot | grep -o '^[^ ]*'`"
	humanreadabledate="`date -d @$seconds '+%a %d.%m.%Y %H:%M'`" # date format: Sun 12.03.2014 12:34
	onlineplayers="`echo $slot | grep -o ' .*$'`"
	outarr="$outarr\n$seconds ${cg}$humanreadabledate${cn}$onlineplayers"
done

# print time slot occupations
echo -e $outarr | sort | grep -o '[^0-9 ].*$' # strip seconds from output

exit 0

