#!/bin/bash

timesfile=times

# clear times file
rm "$timesfile"
for logfile in `ls -1 *.log.gz`
do
	date="`echo $logfile | cut -b-10`"
	while read line
	do
		time="`echo $line | cut -b2-9`"
		seconds=`date -d "$date $time" +%s`
		action="`echo $line | grep -o '\(joined\|left\)'`"
		name="`echo $line | cut -b34- | grep -o '^[^ ]*'`"
		echo "$seconds $action $name" >> $timesfile
	done < <(gzip -dc $logfile | grep '.*Server thread/INFO.* the game$' | grep -v '[<>]')
	# was the server shut down?
	time="`gzip -dc $logfile | grep -E '^[^<>]* Stopping server$' | tail -n 1 | cut -b2-9`"
	if [ -n "$time" ]
	then
		seconds=`date -d "$date $time" +%s`
		echo "$seconds restart" >> $timesfile
	fi
done

exit 0

