#!/bin/bash
# Concatenates all logfiles of a day and draws a histogram of that day.

date="$1"
whitelist="$2"

source utils

# concatenate logs for a whole day into a new .log file
for file in $logfilespath/"$date"*.log.gz; do
	gzip -dc $file >> $logfilespath/"$date".log
done

# create ".scanned" file of the whole day
./scan-one $logfilespath/"$date".log > $logfilespath/"$date"$suffix

# output histogram
./histogram $logfilespath/"$date"$suffix $whitelist

rm $logfilespath/"$date".log $logfilespath/"$date"$suffix # cleanup (or else new content will be added to create an infinite log/scanfile)

exit 0

