#!/bin/bash
# reads a provided "scanfile" and plots it as a histogram using unicode
# by HarHarLinks

let column=0;
scanfile="$1"
whitelist="$2"
curline="";

# coloring
if test -t 1; then
	cr="\e[1;49;31m" # red
	cg="\e[1;49;32m" # green
	cy="\e[1;49;33m" # yellow
	cb="\e[1;49;34m" # blue
	cn="\e[0;0;0m"   # normal/reset
fi

while read wline; do
	curuser=$wline;
	curline="`printf '%16s' $curuser` |";
	case "$curuser" in
	"Offlinegott" | "Moqtah_Laila")
		curline+=$cg;
		;;
	"gjum")
		curline+=$cb;
		;;
	"HHL")
		curline+=$cy;
		;;
	esac
	while read line; do
		if [ "$line" == '=== onlinetimes ===' ]; then
			break
		fi
		if `echo "$line" | grep -q " $curuser"`; then
			#seconds="`echo "$line" | awk ...`" # TODO put time this player played during this slot after its name
			#ontime="$(( $seconds / 60 ))"
			full='\xE2\x96\x88'
			#half='\xE2\x96\x84'
			#if [ $ontime -gt 45 ]; then
				curline+=" $full$full"
			#elif [ $ontime -gt 15 ]; then
			#	curline+=' $half$half';
			#else
			#	curline+=' __';
			#fi
		else curline+="   ";
		fi
	done < "$scanfile"
	echo -e "$curline$cn";

done < <(cat $whitelist)
echo "            time | 00 01 02 03 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
exit 0
