#!/bin/bash
# reads a provided "scanfile" and plots it as a histogram using unicode
# by HarHarLinks

scanfile="$1"
whitelist="$2"

# coloring
if test -t 1; then
	cr="\e[1;49;31m" # red
	cg="\e[1;49;32m" # green
	cy="\e[1;49;33m" # yellow
	cb="\e[1;49;34m" # blue
	cn="\e[0;0;0m"   # normal/reset
fi

filltimeline=true # true for the first player

# print histogram line for each user
while read curuser; do
	if [ -n "$curuser" ]; then # catch empty lines
		curline="`printf '%16s' $curuser` |";
		case "$curuser" in
			"Offlinegott" | "Moqtah_Laila")
				curline+=$cg;
				;;
			"gjum")
				curline+=$cb;
				;;
			"HHL")
				curline+=$cy;
				;;
		esac
		# read the scanfile
		while read line; do
			if `echo "$line" | grep -q '^=== '`; then # end of relevant lines
				break
			fi
			if $filltimeline; then # add the hour to the timeline
				linetime="`echo "$line" | grep -o "^[^ ]*"`"
				slothour="`date -d "@$linetime" +%H`"
				timeline+=" $slothour"
			fi
			# print bar according to how long the player was online during this slot
			if `echo "$line" | grep -q " $curuser"`; then
				seconds="`echo "$line" | grep -o " $curuser [0-9]*" | cut -d' ' -f3`"
				ontime="$(( $seconds / 60 ))"
				full='\xE2\x96\x88'
				seveneights='\xE2\x96\x87'
				threequaters='\xE2\x96\x86'
				fiveeights='\xE2\x96\x85'
				half='\xE2\x96\x84'
				threeeights='\xE2\x96\x83'
				quarter='\xE2\x96\x82'
				eigth='\xE2\x96\x82'
				if [ $ontime -gt 56 ]; then
					curline+=" $full$full"
				elif [ $ontime -gt 49 ]; then
					curline+=" $seveneights$seveneights";
				elif [ $ontime -gt 42 ]; then
					curline+=" $threequarters$threequarters";
				elif [ $ontime -gt 35 ]; then
					curline+=" $fiveeights$fiveeights";
				elif [ $ontime -gt 28 ]; then
					curline+=" $half$half";
				elif [ $ontime -gt 21 ]; then
					curline+=" $threeeights$threeeights";
				elif [ $ontime -gt 14 ]; then
					curline+=" $quarter$quarter";
				elif [ $ontime -gt 7 ]; then
					curline+=" $eigth$eigth";
				else
					curline+=' __';
				fi
			else curline+="   ";
			fi
		done < "$scanfile"
		echo -e "$curline$cn";
		filltimeline=false
	fi
done < $whitelist
echo "            time |$timeline"
exit 0
