#!/bin/bash
# Reads the scanfile of a given day and plots it as a histogram using unicode.

source utils

today="$1" # year-month-day of the logfiles to read
if [ -z "$today" ]; then
	today="`date +%Y-%m-%d`"
fi
scanfile="$logfilespath/$today$suffix"

./histogram "$scanfile" "$2"
