#!/bin/bash
# Creates a list of times every player in the whitelist has played in total.

source utils # include utility functions

# init
declare -A onlinetotal # seconds each player was online

filelist="$logfilespath/*$suffix"

# {{{ look at all logfiles
for scanfile in $filelist; do
	readthisline=false # skip all lines before and including the onlinetimes marker
	# for each player, add the online time
	while read line; do
		if $readthisline; then
			if [[ "$line" == ===* ]]; then
				break # all relevant lines scanned
			fi
			name="`echo "$line" | cut -d' ' -f1`"
			seconds="`echo "$line" | cut -d' ' -f2`"
			if [ -z "${onlinetotal["$name"]}" ]; then
				onlinetotal["$name"]=$seconds
			else
				onlinetotal["$name"]=$(( $seconds + ${onlinetotal["$name"]} ))
			fi
		elif [[ "$line" == ===\ onlinetimes\ === ]]; then
			readthisline=true
		fi
	done < "$scanfile"
done # }}}

# {{{ print results
for name in "${!onlinetotal[@]}"; do
	seconds="${onlinetotal["$name"]}"
	printf '%10d %-16s %s\n' "$seconds" "$name" "`convertsecs "$seconds"`"
done | sort -nr | cut -b12- # sort descending, natural numbers ordering
# }}}

exit 0

