#!/usr/bin/env python2
import sys
import os
import time
from glob import glob
import LogProcessor

if len(sys.argv) < 2:
    print('Usage %s <path/to/logs/> [YYYY-MM-DD = today]' % sys.argv[0])
    sys.exit(0)
logPath = sys.argv[1]
dateString = sys.argv[2] if len(sys.argv) > 2 else time.strftime("%Y-%m-%d", time.localtime(os.path.getmtime(logPath + '/latest.log')))

processor = LogProcessor.LogProcessor()
for log in glob(logPath + '/' + dateString + '*.log.gz'):
    processor.processFile(log)
if len(sys.argv) <= 2: # no date given, today's events are in latest.log
    processor.processFile(logPath + '/latest.log')

processor.printTotalTimes()

