#!/bin/bash
# Creates a list of times every player in the whitelist has played at one day.

source utils # include utility functions

# init
declare -A onlinetoday # seconds each player was online today

# arguments
today="$1" # year-month-day of the logfiles to read
if [ -z "$today" ]; then
	today="`date +%Y-%m-%d`"
fi
scanfile="$logfilespath/$today$suffix"

# {{{ look at the logfile of today
readthisline=false # skip all lines before and including the onlinetimes marker
# for each player, add the online time
while read line; do
	if $readthisline; then
		if [[ "$line" == ===* ]]; then
			break # all relevant lines scanned
		fi
		name="`echo "$line" | cut -d' ' -f1`"
		seconds="`echo "$line" | cut -d' ' -f2`"
		if [ -z "${onlinetoday["$name"]}" ]; then
			onlinetoday["$name"]=$seconds
		else
			onlinetoday["$name"]=$(( $seconds + ${onlinetoday["$name"]} ))
		fi
	elif [[ "$line" == ===\ onlinetimes\ === ]]; then
		readthisline=true
	fi
done < "$scanfile"
# }}}

# {{{ print results
for name in "${!onlinetoday[@]}"; do
	seconds="${onlinetoday["$name"]}"
	printf '%10d %-16s %s\n' "$seconds" "$name" "`convertsecs "$seconds"`"
done | sort -nr | cut -b12- # sort descending, natural numbers ordering
# }}}

exit 0

