#!/usr/bin/env python3

from datetime import datetime, timedelta
from time import strftime
import logalyzer
import timeline
import sys

# apply args
if len(sys.argv) < 1:
    print('Usage: %s <path to log files>', sys.rgv[0])
    sys.exit(0)
logs = logalyzer.LogDirectory(sys.argv[1])

if len(sys.argv) < 3:
    to_date = datetime.now() + timedelta(hours=1)
elif len(sys.argv) > 2:
    to_date = datetime.strptime(sys.argv[2], '%Y-%m-%d') + timedelta(hours=1)
from_date = (to_date - timedelta(days=1))
to_day = strftime('%Y-%m-%d', to_date.timetuple())
from_day = strftime('%Y-%m-%d', from_date.timetuple())
to_time = strftime('%H:%M:%S', to_date.timetuple())
from_time = strftime('%H:%M:%S', from_date.timetuple())

#get data
logs = logalyzer.LogDirectory(sys.argv[1])
draw_data = timeline.get_draw_data(logs, from_day, to_day, from_time, to_time)
timeline.draw_timeline(draw_data, 'timeline_lastDay.png', 2000, from_day+' '+strftime('%H:%M:%S', (from_date - timedelta(hours=1)).timetuple())+' - '+to_day+' '+strftime('%H:%M:%S', (to_date - timedelta(hours=1)).timetuple()))
