#!/bin/bash

# configuration
suffix=.scanned
logfilespath='../logs/'
slotsec=3600 # 3600 seconds/hour, 86400 seconds/day

# useful constants

# {{{ Is output a tty?
istty=false
if test -t 1; then
	istty=true
fi # }}}

# {{{ coloring
if $istty; then
	cr="\e[1;49;31m" # red
	cg="\e[1;49;32m" # green
	cy="\e[1;49;33m" # yellow
	cb="\e[1;49;34m" # blue
	cn="\e[0;0;0m"   # normal/reset
fi #}}}

# useful functions

convertsecs() { # {{{ convert seconds into hours:minutes:seconds
	h=`expr $1 / 3600`
	m=`expr $1 % 3600 / 60`
	s=`expr $1 % 60`
	printf "%02d:%02d:%02d\n" $h $m $s
} # }}}

getlogfilesoftoday() { # {{{ $1=date
	if [ "$1" == `date +%Y-%m-%d` ]; then
		echo "$logfilespath/$1*.log.gz $logfilespath/latest.log"
	else
		echo "$logfilespath/$1*.log.gz"
	fi
} # }}}

